In [63]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [64]:
df=pd.read_csv("student.csv");

In [65]:
df.shape

(12, 5)

In [66]:
df.head()

   StudentID    Name   Age  Gender  Marks
0        101     Ali  20.0    Male   85.0
1        102   Ahmed  21.0    Male   78.0
2        103    Sara   NaN  Female   92.0
3        104  Ayesha  19.0  Female    NaN
4        105   Bilal  -5.0    Male   88.0

In [67]:
df.info() #gives us data types of columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  12 non-null     int64
 1   Name       12 non-null     object
 2   Age        10 non-null     float64
 3   Gender     12 non-null     object
 4   Marks      11 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 612.0+ bytes

In [68]:
df.dtypes #tells us data types

StudentID      int64
Name          object
Age          float64
Gender        object
Marks        float64
dtype: object

In [69]:
df.nunique() # returns unique values count

StudentID    11
Name         11
Age           6
Gender        5
Marks        10
dtype: int64

In [70]:
df.duplicated().sum()

1

In [71]:
df.drop_duplicates(inplace=True)

In [72]:
df.isnull().sum()

StudentID    0
Name         0
Age          2
Gender       0
Marks        1
dtype: int64

In [73]:
#df.dropna(how="any",inplace=True) #drop all null values if even 1 column is nan
df.dropna(how='all' , inplace=True) #drop all null values if all row is nan

In [74]:
for col in df.columns: #columns will give us columns 
    if df[col].dtype=="object":
        df[col]=df[col].fillna(df[col].mode()[0])  # fillna will replace nan values with mode if object 
    else:
        df[col]=df[col].fillna(df[col].median()) #and with median if int or float data type

In [75]:
df.head()

   StudentID    Name   Age  Gender  Marks
0        101     Ali  20.0    Male   85.0
1        102   Ahmed  21.0    Male   78.0
2        103    Sara  20.0  Female   92.0
3        104  Ayesha  19.0  Female   86.5
4        105   Bilal  -5.0    Male   88.0

In [76]:
df.tail()

    StudentID    Name   Age  Gender  Marks
6         107  Fatima  20.0  female   81.0
7         108    Zain  20.0    Male   75.0
8         109    Noor  23.0  Female   90.0
10        110  Hassan  21.0       M   84.0
11        111    Sana  20.0       F   89.0

In [77]:
df.loc[df["Age"]<0,"Age"]=df["Age"].mean() # short for location 
print(df["Age"])

0     20.000000
1     21.000000
2     20.000000
3     19.000000
4     18.272727
5     22.000000
6     20.000000
7     20.000000
8     23.000000
10    21.000000
11    20.000000
Name: Age, dtype: float64

In [78]:
df["Gender"].replace({"M": "Male", "F": "Female", "female": "Female", "male": "Male"}, inplace=True)
print(df["Gender"])

0       Male
1       Male
2     Female
3     Female
4       Male
5       Male
6     Female
7       Male
8     Female
10      Male
11    Female
Name: Gender, dtype: object

C:\Users\hp\AppData\Local\Temp\ipykernel_13936\908987079.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].replace({"M": "Male", "F": "Female", "female": "Female", "male": "Male"}, inplace=True)

In [79]:
df.describe()

        StudentID        Age       Marks
count   11.000000  11.000000   11.000000
mean   106.000000  20.388430  122.590909
std      3.316625   1.316200  125.279052
min    101.000000  18.272727   75.000000
25%    103.500000  20.000000   82.500000
50%    106.000000  20.000000   86.500000
75%    108.500000  21.000000   89.500000
max    111.000000  23.000000  500.000000

In [80]:

for col in df.columns:
 if df[col].dtypes!="object":
    Q1 = df['Marks'].quantile(0.25)
    Q3 = df['Marks'].quantile(0.75)
    IQR = Q3-Q1
    lower_bound = Q1 - 1.5*IQR
    upper_bound = Q3 + 1.5*IQR
    df = df[(df['Marks'] >= lower_bound)
     &(df['Marks'] <= upper_bound)]

In [81]:
le=LabelEncoder()
df["Gender"]=le.fit_transform(df["Gender"])
print(df["Gender"])

0     1
1     1
2     0
3     0
4     1
6     0
7     1
8     0
10    1
11    0
Name: Gender, dtype: int32

In [83]:

df.to_csv('Student_Updated.csv' , index=False)